#!/bin/bash
# generate-corefile.sh — Generate CoreDNS Corefile for split DNS
#
# Reads publisher configuration from stdin (JSON) and generates a Corefile
# that forwards zone queries to local proxy ports (one per publisher).
#
# Each publisher with dns_zones gets a unique proxy port: 5300 + publisher_index.
# The proxy (started by setup-ns-dns.sh) bridges host → publisher's namespace DNS.
#
# Usage: echo '<publishers_json>' | ./generate-corefile.sh
#
# Input JSON format (array of publishers):
# [
#   {
#     "id": "a1b2c3d4-...",
#     "publisher_index": 1,
#     "name": "office-madrid",
#     "dns_zones": ["internal.company.com", "corp.company.com"],
#     "dns_server": "10.0.0.53"
#   },
#   {
#     "id": "e5f6g7h8-...",
#     "publisher_index": 2,
#     "name": "office-london",
#     "dns_zones": ["internal.widgets.co.uk"],
#     "dns_server": "10.0.0.1"
#   }
# ]
#
# Output: /etc/wireztna/Corefile (or path given as $1)

set -euo pipefail

OUTPUT_FILE="${1:-/etc/wireztna/Corefile}"

# Read JSON from stdin
INPUT_JSON=$(cat)

if [ -z "$INPUT_JSON" ]; then
    echo "ERROR: No JSON input received on stdin"
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required"
    exit 1
fi

echo "[*] Generating CoreDNS Corefile: $OUTPUT_FILE"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# ─── Header ───
cat > "$OUTPUT_FILE" << 'EOF'
# WireZTNA CoreDNS Configuration — AUTO-GENERATED
# Split DNS: publisher zones forwarded to local proxy ports (socat → namespace DNS)
# DO NOT EDIT — regenerated by reconciler on each config change

EOF

# ─── Per-publisher zone blocks ───
# Only process publishers that have both dns_zones and dns_server
echo "$INPUT_JSON" | jq -c '.[] | select(.dns_zones != null and .dns_server != null and (.dns_zones | length) > 0)' | while read -r pub; do
    PUB_NAME=$(echo "$pub" | jq -r '.name // .id')
    PUB_INDEX=$(echo "$pub" | jq -r '.publisher_index')
    PROXY_PORT=$((5300 + PUB_INDEX))
    ZONES=$(echo "$pub" | jq -r '.dns_zones[]')

    while IFS= read -r zone; do
        [ -z "$zone" ] && continue
        cat >> "$OUTPUT_FILE" << EOF
# Publisher: $PUB_NAME (index $PUB_INDEX, proxy port $PROXY_PORT)
${zone} {
    forward . 127.0.0.1:${PROXY_PORT}
    cache 30
    log
    errors
}

EOF
    done <<< "$ZONES"
done

# ─── Default catch-all zone ───
cat >> "$OUTPUT_FILE" << 'EOF'
# Default: all other queries go to public DNS
. {
    forward . 8.8.8.8 1.1.1.1
    cache 60
    log
    errors
    reload 5s
}
EOF

echo "[✓] Corefile generated: $OUTPUT_FILE"
