#!/bin/bash
# generate-rules.sh — Generate nftables rules from a policy JSON file
#
# Input: JSON policy file with user→namespace access mappings
# Output: nftables ruleset file ready for atomic apply
#
# Usage: sudo ./generate-rules.sh <policy-json> [output-file]
#
# Policy JSON format:
# {
#   "policies": [
#     {"client_ip": "10.200.0.10", "allowed_veths": ["veth-site-madrid-h", "veth-site-london-h"]},
#     {"client_ip": "10.200.0.11", "allowed_veths": ["veth-site-madrid-h"]}
#   ]
# }

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <policy-json> [output-file]"
    exit 1
fi

POLICY_FILE="$1"
OUTPUT_FILE="${2:-/etc/nftables.d/wireztna-policies.nft}"
WG_INTERFACE="wg-clients"

# ─── Validate input ───
if [ ! -f "$POLICY_FILE" ]; then
    echo "ERROR: Policy file not found: $POLICY_FILE"
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required. Install with: apt install jq"
    exit 1
fi

echo "[*] Generating nftables rules from: $POLICY_FILE"

# ─── Generate ruleset ───
mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" << 'EOF'
#!/usr/sbin/nft -f
# WireZTNA Policy Rules — AUTO-GENERATED, DO NOT EDIT
# Generated by generate-rules.sh

table inet wireztna {
    chain forward {
        type filter hook forward priority 0; policy drop;

        # Allow established/related connections (return traffic)
        ct state established,related accept

        # Allow traffic from overlay clients to authorized namespaces
EOF

# ─── Parse policies and generate rules ───
jq -c '.policies[]' "$POLICY_FILE" | while read -r policy; do
    CLIENT_IP=$(echo "$policy" | jq -r '.client_ip')
    VETHS=$(echo "$policy" | jq -r '.allowed_veths[]')
    
    while IFS= read -r veth; do
        echo "        iifname \"$WG_INTERFACE\" ip saddr $CLIENT_IP oifname \"$veth\" accept" >> "$OUTPUT_FILE"
    done <<< "$VETHS"
done

# ─── Add return path (from namespace veths back to overlay) ───
cat >> "$OUTPUT_FILE" << 'EOF'

        # Allow return traffic from namespaces to overlay
        oifname "wg-clients" ct state established,related accept

        # Everything else is dropped (default policy)
    }
}
EOF

echo "[✓] Rules generated: $OUTPUT_FILE"
echo "    Apply with: sudo ./apply-rules.sh"
